### ISSUE TITLE
Customisation options

### ISSUE THREAD

**Issue by mariuspena** [AppliedRecognition/Ver-ID-UI-Android#5]
Hi,

I want to implement a liveness test with the following features:
1. must work in a fragment (not open another activity)
2. must use own drawables for instructions for when to turn the head.
3. customise and localise texts for instructions
4. optional - want to use cameraView library https://github.com/natario1/CameraView

what are my options ?
thank you

**Comment by jakubdolejs** [comment]
Hi Marius,

All this can be done with some work on your part.

This project should help you to get started: https://github.com/AppliedRecognition/Ver-ID-Kiosk-Android

In a nutshell, you'll want to create your own version of [VerIDSessionFragment](https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/master/veridui/src/api21/java/com/appliedrec/verid/ui/VerIDSessionFragment.java). You can either extend this class or create a brand new fragment that implements the [IVerIDSessionFragment2](https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/f94ba501cbc24577cb3742ffb1308fb343785b1f/veridui/src/main/java/com/appliedrec/verid/ui/IVerIDSessionFragment2.java) interface. If it's possible, have your activity extend [VerIDSessionActivity](https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/master/veridui/src/main/java/com/appliedrec/verid/ui/VerIDSessionActivity.java). [UserIdentificationActivity](https://github.com/AppliedRecognition/Ver-ID-Kiosk-Android/blob/master/app/src/main/java/com/appliedrec/verid/kiosk/UserIdentificationActivity.java) in the Kiosk app should give you an idea what to do. Otherwise take a look at [VerIDSessionActivity](https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/master/veridui/src/main/java/com/appliedrec/verid/ui/VerIDSessionActivity.java) and copy some of the code as needed. You'll have to create an instance of [SessionTask](https://appliedrecognition.github.io/Ver-ID-UI-Android/com.appliedrec.verid.core.SessionTask.html).

As for localisation, the default session activity accepts instances of [TranslatedStrings](https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/master/veridui/src/main/java/com/appliedrec/verid/ui/TranslatedStrings.java). You can read more about translations [here](https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/master/Translating-Ver-ID-UI.md).

There is no reason why you shouldn't be able to use your own camera view as long as it can supply images to the face detection.

Our team can help you with all this. Please [email us](mailto:support@appliedrec.com) with more details of your project and we'll be happy to set up a phone call to discuss your options.
